### ISSUE TITLE
'run' CommandNotFound Error when running VBiosFinder tool

### ISSUE THREAD

**Issue by RebelLion420** [thoughtbot/terrapin#14]
I just installed Ruby and the required gems in Manjaro Linux, and added the ruby path to my $PATH but I am still getting these errors. I have not found any other help related to my trouble that I haven't tried yet so I am asking here as a last resort. Here is the error output:

```
Traceback (most recent call last):
	12: from _init.rb:7:in `<main>'
	11: from /tmp/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	10: from /tmp/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 9: from /tmp/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /tmp/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 7: from /tmp/VBiosFinder/src/cli.rb:36:in `extract'
	 6: from /tmp/VBiosFinder/src/methods.rb:43:in `run'
	 5: from /tmp/VBiosFinder/src/methods.rb:43:in `each'
	 4: from /tmp/VBiosFinder/src/methods.rb:45:in `block in run'
	 3: from /tmp/VBiosFinder/src/extraction.rb:8:in `attempt'
	 2: from /tmp/VBiosFinder/src/extraction.rb:8:in `call'
	 1: from /tmp/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
/tmp/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
```

**Comment by RebelLion420** [comment]
My bad, it was an issue with dependencies using VBIOSFinder. Closing now
