### ISSUE TITLE
'run' CommandNotFoundError

### ISSUE THREAD

**Issue by robstove** [thoughtbot/terrapin#8]
We're getting an error when executing the run command from Terrapin. Below is the callstack. Is this a mis-configuration of sorts?

```
Terrapin::CommandNotFoundError
/var/lib/gems/2.3.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run'
/home/ycd/rambleron-web/lib/command.rb:11:in `run'
/home/ycd/rambleron-web/app/jobs/generate_approval_images_job_v2.rb:562:in `create_mark'
```

**Comment by nagendrababu0701** [comment]
How to add $PATH, Could you please help me
